import random
import time
print("Welcome to the Millionaire Game!")
questions = [
# 🍔 FOOD (1–12)
["Which fruit is known as the 'King of Fruits'?", "Apple", "Banana", "Mango", "Orange", 3],
["Which country is famous for pizza?", "India", "Italy", "France", "USA", 2],
["What is the main ingredient of butter?", "Milk", "Oil", "Water", "Flour", 1],
["Which spice is known as red gold?", "Turmeric", "Saffron", "Chili", "Cinnamon", 2],
["Which drink is made from tea leaves?", "Coffee", "Tea", "Juice", "Milkshake", 2],
["Which vitamin is in citrus fruits?", "Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D", 3],
["Which food is rich in protein?", "Rice", "Egg", "Sugar", "Salt", 2],
["Which country is famous for sushi?", "China", "Japan", "Korea", "Thailand", 2],
["What is paneer made from?", "Milk", "Wheat", "Rice", "Oil", 1],
["Which fruit is yellow and curved?", "Apple", "Banana", "Grapes", "Orange", 2],
["Which oil is used for cooking?", "Engine oil", "Olive oil", "Petrol", "Diesel", 2],
["Which sweet is popular in India?", "Pizza", "Burger", "Gulab Jamun", "Pasta", 3],
# 🎬 BOLLYWOOD / MOVIES (13–30)
["Who is known as King Khan?", "Salman Khan", "Shah Rukh Khan", "Aamir Khan", "Saif Ali Khan", 2],
["Which movie features '3 Idiots'?", "PK", "3 Idiots", "Dangal", "Lagaan", 2],
["Who played 'Kabir Singh'?", "Ranbir Kapoor", "Shahid Kapoor", "Varun Dhawan", "Hrithik Roshan", 2],
["Which actress starred in 'Queen'?", "Deepika", "Kangana", "Alia", "Katrina", 2],
["Who is known as Mr. Perfectionist?", "Salman Khan", "Aamir Khan", "SRK", "Akshay Kumar", 2],
["Which movie is about wrestling?", "Dangal", "PK", "War", "Don", 1],
["Who played Iron Man?", "Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo", 2],
["Which movie has character 'Jack Sparrow'?", "Titanic", "Avatar", "Pirates of Caribbean", "Avengers", 3],
["Which Bollywood actor is in 'War'?", "Hrithik Roshan", "Ranveer Singh", "Ajay Devgn", "Tiger Shroff", 1],
["Which movie is about aliens?", "Dangal", "PK", "Sultan", "War", 2],
["Who played Spider-Man (Tom Holland)?", "Andrew Garfield", "Tom Holland", "Tobey Maguire", "Chris Pratt", 2],
["Which actress is in 'Raazi'?", "Alia Bhatt", "Kareena", "Deepika", "Sonam", 1],
["Which movie is about cricket?", "Lagaan", "War", "Pathaan", "Don", 1],
["Who directed 'Inception'?", "Nolan", "Spielberg", "Cameron", "Scorsese", 1],
["Which actor is known for comedy roles?", "Akshay Kumar", "Govinda", "Ajay Devgn", "John Abraham", 2],
["Which movie is about boxing?", "Sultan", "Dangal", "Mary Kom", "War", 3],
["Who played Thor?", "Chris Hemsworth", "Chris Evans", "Tom Holland", "Robert Downey", 1],
["Which movie is about time travel?", "Interstellar", "Inception", "Tenet", "All", 4],
# 💻 OS (31–45)
["What does OS stand for?", "Operating System", "Open System", "Order System", "Output System", 1],
["Which OS is used in Android?", "Windows", "Linux", "Mac", "DOS", 2],
["Which is not an OS?", "Windows", "Linux", "Oracle", "MacOS", 3],
["Which OS is by Apple?", "Windows", "Linux", "MacOS", "Android", 3],
["Which OS is open source?", "Windows", "Linux", "MacOS", "iOS", 2],
["Which manages hardware?", "Compiler", "OS", "Interpreter", "Editor", 2],
["Which OS is for iPhone?", "Android", "iOS", "Linux", "Windows", 2],
["Which OS is used in PCs?", "Windows", "Linux", "Both", "None", 3],
["What is kernel?", "Core of OS", "App", "Game", "File", 1],
["Which OS is command based?", "DOS", "Windows", "Mac", "Linux", 1],
["Which OS supports GUI?", "Windows", "DOS", "None", "Both", 1],
["Which is multitasking OS?", "Windows", "DOS", "None", "Basic", 1],
["Which OS is fastest?", "Depends", "Windows", "Linux", "Mac", 1],
["Which OS manages memory?", "OS", "CPU", "RAM", "Compiler", 1],
["Which OS handles processes?", "OS", "User", "App", "None", 1],
# 🧠 DSA (46–60)
["Which data structure uses FIFO?", "Stack", "Queue", "Tree", "Graph", 2],
["Which uses LIFO?", "Queue", "Stack", "Tree", "Array", 2],
["Which structure stores key-value?", "Array", "HashMap", "Stack", "Queue", 2],
["Which search is fastest?", "Linear", "Binary", "Jump", "DFS", 2],
["Which sorting is fastest avg?", "Bubble", "Merge", "Quick", "Selection", 3],
["Which DS is linear?", "Array", "Tree", "Graph", "Heap", 1],
["Which uses recursion?", "DFS", "BFS", "Array", "Queue", 1],
["Which DS is hierarchical?", "Tree", "Array", "Stack", "Queue", 1],
["Which DS uses nodes?", "Linked List", "Array", "Stack", "Queue", 1],
["Which traversal is BFS?", "Queue", "Stack", "Recursion", "None", 1],
["Which traversal is DFS?", "Stack", "Queue", "Array", "None", 1],
["Which is non-linear DS?", "Tree", "Array", "Stack", "Queue", 1],
["Which DS grows dynamic?", "Linked List", "Array", "Stack", "Queue", 1],
["Which DS uses pointers?", "Linked List", "Array", "Stack", "Queue", 1],
["Which DS is used in recursion?", "Stack", "Queue", "Tree", "Graph", 1],
# 🎯 MIX RANDOM (61–70)
["Which planet is known as Red Planet?", "Earth", "Mars", "Jupiter", "Venus", 2],
["Which is national animal of India?", "Lion", "Tiger", "Elephant", "Dog", 2],
["Which festival is of lights?", "Holi", "Diwali", "Eid", "Christmas", 2],
["Which is largest ocean?", "Atlantic", "Indian", "Pacific", "Arctic", 3],
["Which gas we breathe?", "Oxygen", "CO2", "Nitrogen", "Hydrogen", 1],
["Which is fastest animal?", "Lion", "Tiger", "Cheetah", "Horse", 3],
["Which is capital of India?", "Mumbai", "Delhi", "Kolkata", "Chennai", 2],
["Which is national bird?", "Peacock", "Sparrow", "Eagle", "Crow", 1],
["Which is largest continent?", "Asia", "Europe", "Africa", "Australia", 1],
["Which is smallest number?", "0", "-1", "1", "2", 2],
["What does DBMS stand for?", "Database Management System", "Data Backup Management System", "Database Monitoring System", "Data Management Storage", 1],
["Which language is used to interact with databases?", "HTML", "SQL", "Python", "C++", 2],
["Which of the following is a type of database?", "Relational", "Hierarchical", "Network", "All of the above", 4],
["What is a primary key?", "Unique identifier", "Duplicate value", "Optional field", "None", 1],
["Which normal form removes partial dependency?", "1NF", "2NF", "3NF", "BCNF", 2],
["What does SQL stand for?","Structured Query Language","Simple Query Language","Structured Question Language","System Query Language",1],
["Which command is used to retrieve data?","INSERT","DELETE","SELECT","UPDATE",3],
["Which key is used to link tables?","Primary Key","Foreign Key","Candidate Key","Super Key",2],
["Which operation removes all records from a table?","DELETE","DROP","TRUNCATE","REMOVE",3],
["What is normalization?","Reducing redundancy","Increasing redundancy","Deleting data","None",1],
["Which constraint ensures unique values?","NOT NULL","UNIQUE","CHECK","DEFAULT",2],
["Which SQL clause is used for filtering?","WHERE","GROUP BY","ORDER BY","HAVING",1],
["Which join returns matching records only?","INNER JOIN","LEFT JOIN","RIGHT JOIN","FULL JOIN",1],
["Which command removes table structure?","DELETE","DROP","TRUNCATE","REMOVE",2],
["What is a view?","Virtual table","Real table","Index","Schema",1],
["Which key can have NULL values?","Primary Key","Foreign Key","Candidate Key","Super Key",2],
["Which DBMS model uses tables?","Relational","Hierarchical","Network","Object",1],
["Which function counts rows?","SUM()","COUNT()","AVG()","MAX()",2],
["Which clause sorts results?","ORDER BY","GROUP BY","WHERE","HAVING",1],
["What is indexing?","Faster retrieval","Deleting records","Sorting only","None",1],
["Which normal form removes transitive dependency?","1NF","2NF","3NF","BCNF",3],
["Which command adds new data?","INSERT","UPDATE","SELECT","DELETE",1],
["Which SQL keyword is used for grouping?","GROUP BY","ORDER BY","WHERE","HAVING",1],
["Which key uniquely identifies records?","Primary Key","Foreign Key","Super Key","All",4],
["Which join returns all records from left table?","LEFT JOIN","RIGHT JOIN","INNER JOIN","FULL JOIN",1],
["What is a schema?","Database structure","Table data","Query","Index",1],
["Which command modifies data?","UPDATE","SELECT","INSERT","DELETE",1],
["Which constraint prevents NULL values?","NOT NULL","UNIQUE","CHECK","DEFAULT",1],
["Which clause is used with aggregate functions?","HAVING","WHERE","ORDER BY","LIMIT",1],
["Which SQL statement deletes specific rows?","DELETE","DROP","TRUNCATE","REMOVE",1],
["What is ACID property?","Transaction rules","Data types","Keys","Indexes",1],
["Which property ensures consistency?","Atomicity","Consistency","Isolation","Durability",2],
["Which normal form eliminates repeating groups?","1NF","2NF","3NF","BCNF",1],
["Which key is minimal super key?","Candidate Key","Primary Key","Foreign Key","None",1],
["Which command deletes entire database?","DROP","DELETE","REMOVE","TRUNCATE",1],
["Which SQL function returns average?","AVG()","SUM()","COUNT()","MAX()",1],
["Which clause limits results?","LIMIT","WHERE","HAVING","GROUP",1],
["Which join returns all records?","FULL JOIN","INNER JOIN","LEFT JOIN","RIGHT JOIN",1],
["What is denormalization?","Adding redundancy","Removing redundancy","Deleting tables","None",1],
["Which key references another table?","Foreign Key","Primary Key","Super Key","Candidate Key",1],
["Which clause groups rows?","GROUP BY","ORDER BY","HAVING","WHERE",1],
["Which SQL command creates table?","CREATE","MAKE","BUILD","NEW",1],
["Which command renames table?","ALTER","RENAME","UPDATE","CHANGE",2],
["Which function finds maximum?","MAX()","MIN()","SUM()","AVG()",1],
["Which clause is used after GROUP BY?","HAVING","WHERE","LIMIT","ORDER",1],
["Which key is chosen among candidate keys?","Primary Key","Foreign Key","Super Key","None",1],
["Which SQL statement removes duplicates?","DISTINCT","UNIQUE","REMOVE","DELETE",1],
["Which operation modifies structure?","ALTER","UPDATE","INSERT","DELETE",1],
["Which model is tree structured?","Hierarchical","Relational","Network","Object",1],
["Which command adds column?","ALTER","UPDATE","INSERT","ADD",1],
["Which planet is closest to the Sun?","Earth","Mars","Mercury","Venus",3],
["Which is the largest planet?","Earth","Mars","Jupiter","Saturn",3],
["Which gas do plants absorb?","Oxygen","Carbon Dioxide","Nitrogen","Hydrogen",2],
["Which is the fastest land animal?","Lion","Tiger","Cheetah","Horse",3],
["Which is the largest ocean?","Indian","Atlantic","Pacific","Arctic",3],
["Which country has the largest population?","USA","India","China","Russia",2],
["Which is the national bird of India?","Crow","Peacock","Eagle","Sparrow",2],
["Which festival is known as festival of lights?","Holi","Eid","Diwali","Christmas",3],
["Which is the capital of Japan?","Beijing","Seoul","Tokyo","Bangkok",3],
["Which is the smallest continent?","Asia","Europe","Australia","Africa",3],
["Who is known as King Khan?","Salman Khan","Aamir Khan","Shah Rukh Khan","Saif Ali Khan",3],
["Who played 'Kabir Singh'?","Ranbir Kapoor","Shahid Kapoor","Varun Dhawan","Tiger Shroff",2],
["Which movie is about cricket?","War","Lagaan","Don","Pathaan",2],
["Who directed Inception?","Spielberg","Nolan","Cameron","Scott",2],
["Who played Iron Man?","Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo",2],
["Which movie features '3 Idiots'?","PK","3 Idiots","Dangal","Sultan",2],
["Who is known as Mr Perfectionist?","Salman","SRK","Aamir Khan","Akshay",3],
["Which movie is about boxing?","Sultan","Dangal","Mary Kom","War",3],
["Who played Thor?","Chris Evans","Chris Hemsworth","Tom Holland","Robert Downey",2],
["Which movie is about aliens?","Dangal","PK","Don","War",2],

["Which vitamin is from sunlight?","A","B","C","D",4],
["What is H2O?","Oxygen","Hydrogen","Water","Helium",3],
["Which organ pumps blood?","Brain","Heart","Liver","Kidney",2],
["Which gas do humans breathe?","CO2","Oxygen","Nitrogen","Hydrogen",2],
["What is boiling point of water?","90°C","100°C","80°C","70°C",2],
["Which part of plant makes food?","Root","Stem","Leaf","Flower",3],
["Which is hardest substance?","Iron","Diamond","Gold","Silver",2],
["Which planet is red planet?","Earth","Mars","Venus","Jupiter",2],
["Which is nearest star?","Moon","Sun","Mars","Venus",2],
["Which gas is used in balloons?","Oxygen","Nitrogen","Helium","CO2",3],

["Which sport uses bat and ball?","Football","Cricket","Hockey","Tennis",2],
["How many players in cricket team?","9","10","11","12",3],
["Which country won 2011 cricket WC?","Australia","India","England","Pakistan",2],
["Which sport uses racket?","Football","Tennis","Cricket","Hockey",2],
["Which country is famous for football?","India","Brazil","China","Nepal",2],
["Which sport uses net?","Cricket","Football","Volleyball","Chess",3],
["Which sport is indoor?","Cricket","Football","Chess","Hockey",3],
["Which game has queen piece?","Ludo","Chess","Carrom","Cards",2],
["Which sport uses shuttlecock?","Badminton","Tennis","Cricket","Football",1],
["Which sport uses gloves?","Boxing","Football","Tennis","Chess",1],

["Which company made iPhone?","Samsung","Apple","Google","Microsoft",2],
["Which OS is used in Android?","Windows","Linux","Mac","DOS",2],
["Which device is used to type?","Mouse","Keyboard","Monitor","Printer",2],
["Which is programming language?","HTML","Python","HTTP","URL",2],
["Which stores data permanently?","RAM","ROM","Cache","Register",2],
["Which is search engine?","Chrome","Google","Windows","Linux",2],
["Which is social media app?","Excel","Instagram","Word","PowerPoint",2],
["Which is browser?","Chrome","Windows","Linux","Excel",1],
["Which company owns Windows?","Apple","Google","Microsoft","IBM",3],
["Which is input device?","Monitor","Printer","Keyboard","Speaker",3],

["Which number is even?","3","5","7","8",4],
["Which is smallest number?","1","0","-1","2",3],
["Which is prime number?","4","6","7","8",3],
["Which shape has 3 sides?","Square","Triangle","Circle","Rectangle",2],
["Which is largest number?","10","20","5","15",2],
["Which comes after 9?","10","11","8","12",1],
["Which is odd number?","2","4","6","9",4],
["Which is square number?","3","4","5","6",2],
["Which is multiple of 5?","12","15","18","22",2],
["Which is half of 10?","2","3","5","6",3]
]
Reward = 0.
for i in random.sample(questions, k=len(questions)):
    print(i[0])
    print("1.", i[1])
    print("2.", i[2])
    print("3.", i[3])
    print("4.", i[4])
    print("5.","Exit Game")
    answer = int(input("Enter your answer (1-4): "))
    if answer == i[5]:
        print("Correct!")
        print("Your last safe reward is :", Reward)
        Reward += 1000
        print("Your current reward is :", Reward)
    elif answer in [1, 2, 3, 4]:
        print("Wrong! The correct answer is:", i[i[5]])
        if Reward >= 5000:
            print("You have passed the safety level. Your reward is:", Reward)  
        else:
            print("You have not passed the safety level. Your reward is: 0")
            Reward = 0
    elif answer==5:
        print("You have exited the game.")
        break
    else:
        print("Invalid input. Please enter a number between 1 and 4.")